package com.howin.qiulu.pojo;
// default package
// Generated 2017-4-11 16:17:51 by Hibernate Tools 3.2.1.GA

import java.sql.Timestamp;
import java.util.Date;

/**
 * EvaluationResultId generated by hbm2java
 */
public class EvaluationResultId implements java.io.Serializable {

	private String sellPoint;
	private String simage;
	private long orderId;
	private int skuId;
	private int status;
	private int type;
	private Date createTime;
	private String username;
	private int userId;
	private String headPort;
	public EvaluationResultId() {
	}

	public EvaluationResultId(long orderId, int skuId, int status) {
		this.orderId = orderId;
		this.skuId = skuId;
		this.status = status;
	}

	
	public EvaluationResultId(String sellPoint, String simage, long orderId, int skuId, int status, int type,
			Date createTime, String username, int userId, String headPort) {
		super();
		this.sellPoint = sellPoint;
		this.simage = simage;
		this.orderId = orderId;
		this.skuId = skuId;
		this.status = status;
		this.type = type;
		this.createTime = createTime;
		this.username = username;
		this.userId = userId;
		this.headPort = headPort;
	}

	public String getSellPoint() {
		return this.sellPoint;
	}

	public void setSellPoint(String sellPoint) {
		this.sellPoint = sellPoint;
	}

	public String getSimage() {
		return this.simage;
	}

	public void setSimage(String simage) {
		this.simage = simage;
	}

	public long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(long orderId) {
		this.orderId = orderId;
	}

	public int getSkuId() {
		return this.skuId;
	}

	public void setSkuId(int skuId) {
		this.skuId = skuId;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}
	
	

	public int getType() {
		return type;
	}

	public void setType(int type) {
		this.type = type;
	}
	
	
	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	
	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public int getUserId() {
		return userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getHeadPort() {
		return headPort;
	}

	public void setHeadPort(String headPort) {
		this.headPort = headPort;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((createTime == null) ? 0 : createTime.hashCode());
		result = prime * result + ((headPort == null) ? 0 : headPort.hashCode());
		result = prime * result + (int) (orderId ^ (orderId >>> 32));
		result = prime * result + ((sellPoint == null) ? 0 : sellPoint.hashCode());
		result = prime * result + ((simage == null) ? 0 : simage.hashCode());
		result = prime * result + skuId;
		result = prime * result + status;
		result = prime * result + type;
		result = prime * result + userId;
		result = prime * result + ((username == null) ? 0 : username.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		EvaluationResultId other = (EvaluationResultId) obj;
		if (createTime == null) {
			if (other.createTime != null)
				return false;
		} else if (!createTime.equals(other.createTime))
			return false;
		if (headPort == null) {
			if (other.headPort != null)
				return false;
		} else if (!headPort.equals(other.headPort))
			return false;
		if (orderId != other.orderId)
			return false;
		if (sellPoint == null) {
			if (other.sellPoint != null)
				return false;
		} else if (!sellPoint.equals(other.sellPoint))
			return false;
		if (simage == null) {
			if (other.simage != null)
				return false;
		} else if (!simage.equals(other.simage))
			return false;
		if (skuId != other.skuId)
			return false;
		if (status != other.status)
			return false;
		if (type != other.type)
			return false;
		if (userId != other.userId)
			return false;
		if (username == null) {
			if (other.username != null)
				return false;
		} else if (!username.equals(other.username))
			return false;
		return true;
	}

	
	

	

	

	
	

	
	

	

	

}