package com.howin.qiulu.pojo;
import java.sql.Timestamp;
import java.util.Date;

// default package
// Generated 2017-4-11 16:17:51 by Hibernate Tools 3.2.1.GA

/**
 * EvaluationResult generated by hbm2java
 */
public class EvaluationResult implements java.io.Serializable {

	private EvaluationResultId id;
	private Integer commodityScore;
	private Date time;
	private String image;
	private String content;
	private Integer etype;
	public EvaluationResult() {
	}
	
	
	public EvaluationResult(EvaluationResultId id, Integer commodityScore, Date time, String image, String content,
			Integer etype) {
		super();
		this.id = id;
		this.commodityScore = commodityScore;
		this.time = time;
		this.image = image;
		this.content = content;
		this.etype = etype;
	}


	public EvaluationResult(EvaluationResultId id) {
		this.id = id;
	}

	public EvaluationResultId getId() {
		return this.id;
	}

	public void setId(EvaluationResultId id) {
		this.id = id;
	}

	public Integer getCommodityScore() {
		return commodityScore;
	}

	public void setCommodityScore(Integer commodityScore) {
		this.commodityScore = commodityScore;
	}

	public Date getTime() {
		return time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public String getImage() {
		return image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}


	public Integer getEtype() {
		return etype;
	}


	public void setEtype(Integer etype) {
		this.etype = etype;
	}
	
	 
}
