package com.howin.qiulu.pojo;
// Generated 2017-4-22 18:10:56 by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * OnSale generated by hbm2java
 */
public class OnSale implements java.io.Serializable {

	private Integer id;
	private int skuId;
	private Date stime;
	private Date etime;
	private Float price;
	private Integer status;

	public OnSale() {
	}

	public OnSale(int skuId) {
		this.skuId = skuId;
	}

	public OnSale(int skuId, Date stime, Date etime, Float price, Integer status) {
		this.skuId = skuId;
		this.stime = stime;
		this.etime = etime;
		this.price = price;
		this.status = status;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getSkuId() {
		return this.skuId;
	}

	public void setSkuId(int skuId) {
		this.skuId = skuId;
	}

	public Date getStime() {
		return this.stime;
	}

	public void setStime(Date stime) {
		this.stime = stime;
	}

	public Date getEtime() {
		return this.etime;
	}

	public void setEtime(Date etime) {
		this.etime = etime;
	}

	public Float getPrice() {
		return this.price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
