package com.howin.qiulu.pojo;
// default package
// Generated 2017-4-6 16:17:03 by Hibernate Tools 3.2.1.GA

/**
 * OrderResult generated by hbm2java
 */
public class OrderResult implements java.io.Serializable {

	private OrderResultId id;

	public OrderResult() {
	}

	public OrderResult(OrderResultId id) {
		this.id = id;
	}

	public OrderResultId getId() {
		return this.id;
	}

	public void setId(OrderResultId id) {
		this.id = id;
	}

}
