package com.howin.qiulu.pojo;
// default package

// Generated 2017-4-6 16:17:03 by Hibernate Tools 3.2.1.GA

import java.sql.Timestamp;

/**
 * OrderResultId generated by hbm2java
 */
public class OrderResultId implements java.io.Serializable {

	private int id;
	private Long orderId;
	private Integer userId;
	private Timestamp createTime;
	private float price;
	private int number;
	private Float total;
	private Integer postage;
	private Integer status;
	private int skuId;
	private String image;
	private String sellPoint;
	private String receiver;

	public OrderResultId() {
	}

	public OrderResultId(int id, float price, int number, int skuId) {
		this.id = id;
		this.price = price;
		this.number = number;
		this.skuId = skuId;
	}

	public OrderResultId(int id, Long orderId, Integer userId, Timestamp createTime, float price, int number,
			Float total, Integer postage, Integer status, int skuId, String image, String sellPoint, String receiver) {
		this.id = id;
		this.orderId = orderId;
		this.userId = userId;
		this.createTime = createTime;
		this.price = price;
		this.number = number;
		this.total = total;
		this.postage = postage;
		this.status = status;
		this.skuId = skuId;
		this.image = image;
		this.sellPoint = sellPoint;
		this.receiver = receiver;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Timestamp getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Timestamp createTime) {
		this.createTime = createTime;
	}

	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	public int getNumber() {
		return this.number;
	}

	public void setNumber(int number) {
		this.number = number;
	}

	public Float getTotal() {
		return this.total;
	}

	public void setTotal(Float total) {
		this.total = total;
	}

	public Integer getPostage() {
		return this.postage;
	}

	public void setPostage(Integer postage) {
		this.postage = postage;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public int getSkuId() {
		return this.skuId;
	}

	public void setSkuId(int skuId) {
		this.skuId = skuId;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public String getSellPoint() {
		return this.sellPoint;
	}

	public void setSellPoint(String sellPoint) {
		this.sellPoint = sellPoint;
	}

	public String getReceiver() {
		return receiver;
	}

	public void setReceiver(String receiver) {
		this.receiver = receiver;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((createTime == null) ? 0 : createTime.hashCode());
		result = prime * result + id;
		result = prime * result + ((image == null) ? 0 : image.hashCode());
		result = prime * result + number;
		result = prime * result + ((orderId == null) ? 0 : orderId.hashCode());
		result = prime * result + ((postage == null) ? 0 : postage.hashCode());
		result = prime * result + Float.floatToIntBits(price);
		result = prime * result + ((receiver == null) ? 0 : receiver.hashCode());
		result = prime * result + ((sellPoint == null) ? 0 : sellPoint.hashCode());
		result = prime * result + skuId;
		result = prime * result + ((status == null) ? 0 : status.hashCode());
		result = prime * result + ((total == null) ? 0 : total.hashCode());
		result = prime * result + ((userId == null) ? 0 : userId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		OrderResultId other = (OrderResultId) obj;
		if (createTime == null) {
			if (other.createTime != null)
				return false;
		} else if (!createTime.equals(other.createTime))
			return false;
		if (id != other.id)
			return false;
		if (image == null) {
			if (other.image != null)
				return false;
		} else if (!image.equals(other.image))
			return false;
		if (number != other.number)
			return false;
		if (orderId == null) {
			if (other.orderId != null)
				return false;
		} else if (!orderId.equals(other.orderId))
			return false;
		if (postage == null) {
			if (other.postage != null)
				return false;
		} else if (!postage.equals(other.postage))
			return false;
		if (Float.floatToIntBits(price) != Float.floatToIntBits(other.price))
			return false;
		if (receiver == null) {
			if (other.receiver != null)
				return false;
		} else if (!receiver.equals(other.receiver))
			return false;
		if (sellPoint == null) {
			if (other.sellPoint != null)
				return false;
		} else if (!sellPoint.equals(other.sellPoint))
			return false;
		if (skuId != other.skuId)
			return false;
		if (status == null) {
			if (other.status != null)
				return false;
		} else if (!status.equals(other.status))
			return false;
		if (total == null) {
			if (other.total != null)
				return false;
		} else if (!total.equals(other.total))
			return false;
		if (userId == null) {
			if (other.userId != null)
				return false;
		} else if (!userId.equals(other.userId))
			return false;
		return true;
	}

}