package com.howin.qiulu.pojo;
// Generated 2017-3-30 12:57:38 by Hibernate Tools 3.2.1.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SkuFavorites generated by hbm2java
 */

public class SkuFavorites implements java.io.Serializable {

	private SkuFavoritesId id;

	public SkuFavorites() {
	}

	public SkuFavorites(SkuFavoritesId id) {
		this.id = id;
	}

	public SkuFavoritesId getId() {
		return id;
	}

	public void setId(SkuFavoritesId id) {
		this.id = id;
	}

}
